gift_attribution_controllers:
    resource:
        path: ../src/Gift/Attribution/Infrastructure/Adapter/In/Web/Controller/
        namespace: App\Gift\Attribution\Infrastructure\Adapter\In\Web\Controller
    type: attribute
gift_request_controllers:
    resource:
        path: ../src/Gift/Request/Infrastructure/Adapter/In/Web/Controller/
        namespace: App\Gift\Request\Infrastructure\Adapter\In\Web\Controller
    type: attribute
